# Generated by Django 5.0.3 on 2024-09-17 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_students', models.IntegerField()),
                ('num_teams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('queue_position', models.IntegerField()),
                ('assigned_team', models.IntegerField(blank=True, null=True)),
                ('admin_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrscanner.admininput')),
            ],
        ),
    ]
