# Generated by Django 5.0.3 on 2024-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininput',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
